---

stages:
  - lint
  - build


include:
  - project: 'saltbox/ci-lib'
    file: 'build-image.yml'


Build metric image for tag:
  stage: build
  extends: .build-image
  variables:
    IMAGE_TAG: '$CI_COMMIT_TAG'
    TARGET: main
  rules:
    - if: '$CI_COMMIT_TAG'


Build metric image for branch:
  stage: build
  extends: .build-image
  variables:
    IMAGE_TAG: '$CI_COMMIT_BRANCH'
    TARGET: main
  rules:
    - if: '$CI_COMMIT_BRANCH'


.lint-job:
  stage: lint
  variables:
    PIP_CACHE_DIR: '$CI_PROJECT_DIR/.cache/pip'
    APK_CACHE_DIR: '$CI_PROJECT_DIR/.cache/apk'
    SALTBOX_ENV_FILE: 'tests/test.env'
    SALTBOX_METRIC_ENV_FILE: 'tests/test.env'
  image: python:3.12-alpine
  before_script:
    - mkdir --parents "$APK_CACHE_DIR"
    - apk add --cache-dir "$APK_CACHE_DIR" cargo git
    - pip3 install -e .[dev]
    - python -V
  cache:
    paths:
      - '$PIP_CACHE_DIR'
      - '$APK_CACHE_DIR'


Ruff:
  extends: .lint-job
  script: 'ruff check .'


Mypy:
  extends: .lint-job
  script: 'mypy .'


Trigger API Client build:
  stage: build
  variables:
    MODULE_NAME: saltbox_metric
    SALTBOX_ENV_FILE: 'tests/test.env'
    SALTBOX_METRIC_ENV_FILE: $SALTBOX_ENV_FILE
  trigger:
    include: 
      - project: 'saltbox/ci-lib'
        file: 'gen-api-client.yml'
    strategy: mirror
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push'