[project]
dynamic = ["dependencies", "version"]
name = "saltbox-metric"
requires-python = ">=3.12"
license = { file = 'LICENSE.txt' }
description = ""
readme = "README.md"
classifiers = [
  "Topic :: System :: Systems Administration",
]

[project.urls]
Homepage = "https://saltbox.pro"
Documentation = "https://saltbox.pro"
Repository = "https://dev.saltbox.pro/saltbox/saltbox-metric"

[project.optional-dependencies]
dev = [
  "mypy>=1.15.0",
  "pre-commit",
  "types-redis",
  "python-lsp-server[all]",
  "types-PyYAML",
  "ruff",
  "coverage[toml]>=7.6.11",
  "pytest>=8.3.4",
  "pytest-asyncio>=0.25.3",
  "pytest-cov>=6.0.0",
  "pytest-mock>=3.14.0",
  "pytest-sugar>=1.0.0",
]
reload = [
  "watchfiles"
]

[project.scripts]
saltbox-metric-app = "saltbox_metric.metrics.app:main"

# [metadata]
# url = "https://gitlab.com/saltbox/saltbox-metric"
# version = "attr: package.__version__"

[build-system]
requires = ["setuptools>=75.1.0", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
fallback_version = "0.0.0"

[tool.setuptools.packages.find]
# Explicit package dir for flat-layout
include = ["saltbox_metric", "saltbox_metric.*"]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt", "local_requirements.txt"] }
version = { attr = "saltbox_metric.__version__" }

[tool.ruff]
target-version = "py312"
line-length = 120
src = ["saltbox_metric"]
extend-exclude = ["docs", "env", "__pycache__", "*.egg", "htmlcov"]
respect-gitignore = true
unsafe-fixes = false

[tool.ruff.format]
quote-style = "single"
docstring-code-format = true

[tool.ruff.lint]
select = [
  "B",     # flake8-bugbear
  "C90",   # mccabe
  "C4",    # flake8-comprehensions
  "DTZ",   # flake8-datetimez https://docs.astral.sh/ruff/rules/#flake8-datetimez-dtz
  "EM",    # flake8-errmsg
  "UP",    # pyupgrade
  "FA",    # flake8-future-annotations
  "LOG",   # flake8-logging
  "PTH",   # flake8-use-pathlib
  "ASYNC", #flake8-async
  "G",     # flake8-logging-format
  "E",     # pycodestyle errors
  "F",     # pyflakes
  "I",     # isort
  "S",     # flake8-bandit
  "W",     # pycodestyle warnings
  "N",     # pep8-naming
  "RUF",   # ruff checks
  "TD",    # flake8-todo
]
ignore = [
  # "E402",   # module level import not at top of file
  "E722", # do not use bare except
  "ERA",  # do not autoremove commented out code
  "N818", # error-suffix-on-exception-name
  "UP040", # type instead of TypeAlias PEP 695"
  "TD001", # Invalid TODO tag
  "TD002", # Author name in TODO
  "TD003", # Found TODO in code
  "TD004", # Missing colon in TODO
  "UP017", # Use datetime.UTC alias (not available for 3.10)
  # "G004", # Logging statement uses string formatting
]
fixable = ["ALL"]
unfixable = [
  "F401", # Unused import
  "F841", # Unused variable
  "UP035", # Deprecated import
]

[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = []

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "single"
inline-quotes = "single"
multiline-quotes = "single"

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"tests/**/*.*" = ["S101", "DTZ", "EM101", "RUF012", "E712"]
# "*/models.py" = ["UP007"]
# "*/schemas.py" = ["UP007"]

[tool.ruff.lint.isort]
known-first-party = [
    "saltbox_metric",
    "saltbox_sdk",
    "tests",
]

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.mypy]
check_untyped_defs = true
plugins = ["pydantic.mypy"]
python_version = "3.12"
ignore_missing_imports = false
color_output = true
warn_redundant_casts = true
warn_unused_configs = true
exclude = ["venv/", ".venv/", "tests/*"]
strict = true
disallow_any_generics = false
disallow_incomplete_defs = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
implicit_reexport = false
show_error_codes = true
warn_return_any = true
warn_unreachable = true
warn_unused_ignores = true
mypy_path = '../saltbox-sdk/'

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
minversion = "8.0"
addopts = [
  "--cov=saltbox_metric",
  "--cov-report=term-missing",
  "--durations=5",
  # "--maxfail=1",
  # "--disable-warnings -q",
]
testpaths = ["tests"]
# env_files = [".env.example"]

[tool.coverage.run]
# concurrency = ["gevent"]
# branch = true
source = ["saltbox_metric"]
omit = [
  "main.py",
  "config.py",
  "tests/*",
  "venv/*",
  ".venv/*",
  "**/__init__.py",
]

[tool.coverage.report]
show_missing = true
# fail_under = 60
exclude_lines = [
  "if TYPE_CHECKING:",
  "pragma: no cover",
  "if __name__ == '__main__':",
]
# skip_covered = true
